name: Publish Extension

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create Zip
        run: zip -r extension.zip manifest.json src/ README.md

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: extension.zip
          generate_release_notes: true
